### ISSUE TITLE
Make this repo be the source for OBO

### ISSUE THREAD

**Issue by cmungall** [CTDbase/exposure-ontology-draft#4]
For the OBO library we have

```
build:
  source_url: http://ctdbase.org/reports/CTD_exposure_ontology.obo
  method: obo2owl
```

(to see or edit this go to http://obofoundry.org/ontology/exo.html and click on view or edit)

However, this file has the syntax error reported in #1, which means the OBO central builds fail.

The file on the FTP site should be replaced by the fixed version here, or the OBO entry should point directly here

**Comment by jwiegers** [comment]
The ctdbase.org file has been updated to the fixed version from the repository.

**Comment by cmungall** [comment]
Thanks!
